# site settings
title: "Steas Hemservice"
subtitle: ""
email: steas.hemservice@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Kanngjutargränd 25, 162 57 Vällingby, Stockholm
city: 
Län: 
zip_code: 
country: 
phone: 073-927 41 38 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
